### PR TITLE
Make the theme look more like RubyMine

### PR DESCRIPTION
**Pull request by Ch00k**

### CODE REVIEW

**Comment by 2called-chaos** [comment]
Seriously, what the fuck? That doesn't have to do anything with the railscasts theme, don't you think this would be worth a fork to `sublime-theme-rubymine`?

**Comment by tdm00** [comment]
You're right @2called-chaos that would have been a better option, I should have suggested that. I'll revert this change back.

**Comment by tdm00** [comment]
I've reverted this change.
@Ch00k please feel free to fork and make one that represents RubyMine.

**Comment by Ch00k** [comment]
Sure. I didn't realize that RubyMine's RailsCasts theme is not original RailsCasts.

**Pull request merged**
